config/routes.rb
SampleApp::Application.routes.draw do
  resources :users
  resources :sessions, only: [:new, :create, :destory]
  
  root to: 'static_pages#home'
  match '/signup',  to: 'users#new'
  match '/help',    to: 'static_pages#help'
  match '/about',   to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete
  match '/edit',    to: 'users#edit'
  match '/index',   to: 'static_pagess#users'
  match '/html5',   to: 'users#users_html5'
  

end

app/models/micropost.rb
class Micropost < ActiveRecord::Base
  attr_accessible :content
  belongs_to :user

  validates :content, presence: true, length: { maximum: 140 }
  validates :user_id, presence: true

  default_scope order: 'microposts.created_at DESC'
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  email      :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class User < ActiveRecord::Base
  attr_accessible :name, :email, :password, :password_confirmation
  has_secure_password
  has_many :microposts, dependent: :destroy

  before_save { |user| user.email = email.downcase }
  before_save :create_remember_token # Call method before saving user to DB
  
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence:   true,
                    format:     { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  validates :password, presence: true, length: { minimum: 6 }
  validates :password_confirmation, presence: true
  after_validation { self.errors.messages.delete(:password_digest) }
  #after_validation { self.errors.add(:password_digest, "Please type in a password")}

  


  private # Create hidden private mehods underneeth PRIVATE KEYWORD
  
  def create_remember_token
    self.remember_token = SecureRandom.urlsafe_base64 # save a base64 token into the user "self" remember_token column in the DB
  end 
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include SessionsHelper
  #By including the seesionHelper module in the Application Controller, we're makeing sure the sessionHelper will be exposed to the all MVC
  #By default, all the helpers are available in the views but not in the controllers. 
  #We need the methods from the Sessions helper in both places, so we have to include it explicitly.
  
  
  # Force signout to prevent CSRF  cross-site request forgery safeguard attacks
  def handle_unverified_request
    sign_out
    super
end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def new
    
  end

  def create
    user = User.find_by_email(params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      sign_in user
      #redirect_to user
      redirect_back_or user        
    else
      flash.now[:error]  = 'Invalid email/password combination'
      render 'new'
    end
  end


  def destroy 
  puts "destory function"
  sign_out
  redirect_to root_url
    end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end
  def about
  end
  def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # Checking if a user is signed in
  before_filter :signed_in_user, only: [:edit, :update, :index]
  # Checking if the user that is SIGNED IN is allowed to update,edit a specific profile
  before_filter :correct_user, only: [:edit, :update]
  before_filter :is_admin, only: [:destroy]
  before_filter :signed_in_url_blocked, only: [:new, :create]

  respond_to :html, :xml, :json



  def new
    @user = User.new
  end

  def index
    @users = User.paginate(page: params[:page])
    # Configure Content managment (API) request to display users by their email
    @usermail= params[:email]
    @renderesource = User.find_all_by_email  @usermail #using the _all_by_ allowed me to search by other then ID

    respond_to do |format|
      format.xml {render xml:@renderesource}
      format.json {render json:@renderesource}
      format.html {render html:@users}
    end

  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(params[:user])
      flash_internal_messages("Your profile was changed - Please re-login")
      redirect_to signin_path
    else
      render 'edit'
    end
  end

  def flash_internal_messages(message)
    flash[notice] = message

  end



  def show
    @user = User.find(params[:id])
    @microposts = @user.microposts.paginate(page: params[:page])
  end


  def create
    @user = User.new(params[:user])
    if @user.save
      flash[:success] = "Welcome to MyMaid!"
      sign_in @user
      redirect_to @user

    else
      render 'new'
    end
  end


  def destroy
    User.find(params[:id]).destroy
    flash['success'] = "User was deleted from the DB."
    redirect_to users_url
  end


  # //// Private ////

  private
  def signed_in_url_blocked
    # Redirect signed_in users back to their original location if they try to reach :create or :new

    redirect_to (root_path) unless !signed_in?
  end

  private
  def is_admin
    redirect_to(root_path) unless current_user.admin?

  end

  private

  def correct_user
    @user = User.find(params[:id])
    redirect_to(root_path) unless current_user?(@user)

  end

  def signed_in_user
    # Check if a user is signed in   
    #redirect_to signin_url, notice: "You are not signed in, please sign in." unless signed_in?
    unless signed_in?
      store_location # Store the location of the requested URL 
      redirect_to signin_url, notice: "You are not signed in, please sign in."
    end


  end
end

  

app/helpers/application_helper.rb
module ApplicationHelper
  # Returns the full title on a per-page basis.
  def full_title(page_title)
    base_title = "MyMaid - Job completed!"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end
  def remote_ip
    @remote_ip = request.remote_ip
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper


  def sign_in(user)
    cookies.permanent[:remember_token] = user.remember_token # Store the user.remember_token from the USER DB in a perment cockie for retirval in difrrent pages 
    
    
    # While the the below call the def current_user=(user) by passing an arggument to it,
    # the def current_user=(user) is setting the variable @current_user to the user it got from the the below call, while the third Def
    # defines what is the @current_user BY saying it = to the @current_user if it's not NIL OR pulling it from the DB if it was NIL
        
    self.current_user = user # This assignment calls the current_user definion below
    
      
    end 
    
    def current_user=(user) # define 
    @current_user = user # define @current_user
  end


  def current_user # locate
    @current_user = @current_user ||= User.find_by_remember_token(cookies[:remember_token]) # match to @current_user if it's not NIL (was already found by this DEF) OR we go to the DB and find @current_user in the DB and save it as that @ variable
  end
  
  def current_user?(user)
    user == current_user
  end
  
# Duplication of the sign_in above
  #def sign_in(user)
   #     cookies.permanent[:remember_token] = user.remember_token
    #    self.current_user = user
     #  end
  
  def signed_in?
    !current_user.nil?
  end
  
  def sign_out
    self.current_user = nil
    cookies.delete(:remember_token)
  end
  
    def tokenis
        @tokenis = User.find_by_remember_token(cookies[:remember_token])
    end



def redirect_back_or(default)
    redirect_to(session[:return_to] || default)
    session.delete(:return_to)
  end

  def store_location
    session[:return_to] = request.url
 end
 
  
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper

  # Returns the Gravatar (http://gravatar.com/) for the given user.
  def gravatar_for(user, options = { size: 100, custom_avatar: "mm" })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    avatar = options[:custom_avatar]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?d=#{avatar}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <a href="#">MyMaid</a>
    Cohen Yaniv
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   'about' %></li>
      <li><%= link_to "Contact", 'contact' %></li>
      <li><a href="#">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "Web portal", root_path, id: "logo" %>
      <nav>
        <ul class="nav pull-right">
          <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "Help", help_path %></li>
          <% if signed_in? %>
            <li><%= link_to "Users", users_path %></li>
            <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Account <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Profile", current_user %></li>
                <li><%= puts "current_user" %></li>
                <li><%= link_to "Change Settings" , edit_user_path(current_user) %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "Sign out", signout_path, method: "delete" %>
                </li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to "Sign in", signin_path %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>    
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">

   	<% flash.each do |key, value| %>
    <div class="alert alert-<%= key %>"><%= value %></div>
    <% end %>

      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/microposts/_micropost.html.erb
<li>
  <span class="content"><%= micropost.content %></span>
  <span class="timestamp">
    Posted <%= time_ago_in_words(micropost.created_at) %> ago.
  </span>
</li>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      Please fix the following <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
    
    <li>* <%= msg %></li>
    
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/about.html.erb
<% provide(:title, 'About Us') %>
<h1>About Us</h1>
<p>

</p>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Contact</h1>
<p>

</p>

app/views/static_pages/help.html.erb
<% provide(:title, 'Help') %>
<h1>Help</h1>
<p>

</p>

app/views/static_pages/home.html.erb
<div class="center hero-unit">
  <h1>Welcome to MyMaid!</h1>

  <h2>
    This is the home page for the
    MyMaid Portal web application.
  </h2>
 
  <%= link_to "Sign up now!", signup_path, class: "btn btn-large btn-primary" %>
</div>

app/views/users/_user.html.erb
<li>
  <%= gravatar_for user, size: 52 %>
  <%= link_to user.name, user %>
  <% if current_user.admin? && !current_user?(user)%>
  | <%= link_to "delete", user, method: :delete,
                                               data: { confirm: "You sure?" } %>
      <% end %>
</li>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<h1>Update your profile</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.text_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirm Password" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "Save changes", class: "btn btn-large btn-primary" %>
    <% end %>

    <%= gravatar_for @user %>
    <a href="http://gravatar.com/emails" target="_blank" >change</a>
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h1>All users</h1>
<%= will_paginate %>

<ul class="users">
  <%= render @users %>
</ul>
<%= will_paginate %>

app/views/users/new.html.erb
<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>

      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.text_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "Create my account", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>

<div class="row">
  <aside class="span4">
    <section>
      <h1>
		<%= gravatar_for @user %>
		<%= @user.name %>
      </h1>
    </section>
  </aside>
  <div class="span8">
    <% if @user.microposts.any? %>
        <h3>Microposts (<%= @user.microposts.count %>)</h3>
        <ol class="microposts">
          <%= render @microposts %>
        </ol>
        <%= will_paginate @microposts %>
    <% end %>
  </div>
</div>